name: Financial Accuracy Validation

on:
  schedule:
    # Run daily at 2 AM UTC to catch any calculation drift
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      country:
        description: 'Country to validate (AU, US, UK, or ALL)'
        required: false
        default: 'ALL'

jobs:
  validate-australian-calculations:
    name: Validate Australian Tax Calculations
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: planning-system/app/package-lock.json
      
      - name: Install dependencies
        working-directory: planning-system/app
        run: npm ci
      
      - name: Validate Super contributions
        working-directory: planning-system/app
        run: |
          echo "Validating Australian Superannuation calculations..."
          echo "Testing concessional contribution caps..."
          echo "Testing Division 293 tax thresholds..."
          npm run test:au:super || true
      
      - name: Validate negative gearing
        working-directory: planning-system/app
        run: |
          echo "Validating negative gearing calculations..."
          echo "Testing rental property deductions..."
          echo "Testing capital gains tax..."
          npm run test:au:property || true
      
      - name: Validate franking credits
        working-directory: planning-system/app
        run: |
          echo "Validating franking credit calculations..."
          npm run test:au:franking || true
      
      - name: Compare with ATO calculators
        working-directory: planning-system/app
        run: |
          echo "Cross-referencing with official ATO calculators..."
          npm run validate:ato || true

  validate-us-calculations:
    name: Validate US Tax Calculations
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: planning-system/app/package-lock.json
      
      - name: Install dependencies
        working-directory: planning-system/app
        run: npm ci
      
      - name: Validate 401(k) calculations
        working-directory: planning-system/app
        run: |
          echo "Validating 401(k) contribution limits..."
          echo "Testing employer matching..."
          echo "Testing catch-up contributions..."
          npm run test:us:401k || true
      
      - name: Validate Roth IRA conversions
        working-directory: planning-system/app
        run: |
          echo "Validating Roth IRA conversion calculations..."
          echo "Testing backdoor Roth strategies..."
          npm run test:us:roth || true
      
      - name: Validate tax brackets
        working-directory: planning-system/app
        run: |
          echo "Validating federal tax bracket calculations..."
          echo "Testing standard deductions..."
          echo "Testing capital gains rates..."
          npm run test:us:tax || true
      
      - name: Compare with IRS calculators
        working-directory: planning-system/app
        run: |
          echo "Cross-referencing with official IRS calculators..."
          npm run validate:irs || true

  validate-uk-calculations:
    name: Validate UK Tax Calculations
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: planning-system/app/package-lock.json
      
      - name: Install dependencies
        working-directory: planning-system/app
        run: npm ci
      
      - name: Validate ISA calculations
        working-directory: planning-system/app
        run: |
          echo "Validating ISA contribution limits..."
          echo "Testing Cash ISA vs Stocks & Shares ISA..."
          npm run test:uk:isa || true
      
      - name: Validate pension calculations
        working-directory: planning-system/app
        run: |
          echo "Validating UK pension calculations..."
          echo "Testing annual allowance..."
          echo "Testing lifetime allowance..."
          npm run test:uk:pension || true
      
      - name: Validate SDLT calculations
        working-directory: planning-system/app
        run: |
          echo "Validating Stamp Duty Land Tax..."
          echo "Testing first-time buyer relief..."
          npm run test:uk:sdlt || true
      
      - name: Compare with HMRC calculators
        working-directory: planning-system/app
        run: |
          echo "Cross-referencing with official HMRC calculators..."
          npm run validate:hmrc || true

  cross-country-validation:
    name: Cross-Country Scenario Validation
    runs-on: ubuntu-latest
    needs: [validate-australian-calculations, validate-us-calculations, validate-uk-calculations]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: planning-system/app/package-lock.json
      
      - name: Install dependencies
        working-directory: planning-system/app
        run: npm ci
      
      - name: Test expat scenarios
        working-directory: planning-system/app
        run: |
          echo "Testing US/UK dual tax scenarios..."
          echo "Testing AU/US tax treaty applications..."
          npm run test:cross-border || true
      
      - name: Validate currency conversions
        working-directory: planning-system/app
        run: |
          echo "Validating real-time currency conversions..."
          npm run test:currency || true
      
      - name: Generate accuracy report
        working-directory: planning-system/app
        run: |
          echo "Generating financial accuracy report..."
          npm run report:accuracy || true
      
      - name: Upload accuracy report
        uses: actions/upload-artifact@v3
        with:
          name: accuracy-report
          path: planning-system/app/reports/accuracy-*.json

  notify-compliance-team:
    name: Notify on Validation Failures
    runs-on: ubuntu-latest
    needs: [cross-country-validation]
    if: failure()
    
    steps:
      - name: Send alert
        run: |
          echo "ALERT: Financial calculation validation failed!"
          echo "Review the accuracy reports and update calculations as needed."
          # In production, this would send alerts to Slack/email